trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
  displayName: 'npm install and build'
- task: Npm@1
  inputs:
    command: 'install'

- task: CmdLine@2
  inputs:
    script: 'ng lint'
- task: CmdLine@2
  inputs:
    script: 'ng test'
    
- task: CmdLine@2
  inputs:
    script: 'ng build --prod'